---
author: "Mireille Ngokingha Tchouto and Miha Milek"
output: 
  html_document:
    df_print: paged
    code_folding: hide
params:
  title: "Slingshot"
  git_path: "/mnt/d/work/mireille/fracture-healing-and-aging-scseq"
  figure_out_path: "/mnt/d/onedrive/OneDrive - Charité - Universitätsmedizin Berlin/Third version/Figures/redone/"
  object: "Figures/data/sobj_group_force_final_version.rds"
---

```{r setup, include=FALSE}
library(slingshot)
library(magrittr)
library(pheatmap)
library(tibble)
library(scater)
library(httr)
library(Seurat)
library(dplyr)
library(stringr)
library(ggplot2)
library(cowplot)
library(igraph)
library(Matrix)
library(tidyr)
library(tidyverse)
library(RCurl)
library(plyr)
library(DESeq2)
library(plyr)
library(gtools)
library(biomaRt)
library(AnnotationHub)
library(org.Hs.eg.db)
library(clusterProfiler)
library(org.Mm.eg.db)
library(SingleR)
library(tibble)
library(SingleCellExperiment)
library(scran)
library(apeglm)
library(ashr)
library(sctransform)
library(RColorBrewer)
library(BiocParallel)
library(extrafont)
library(Rttf2pt1) # v1.3.8 or lower
# font_import(paths="/mnt/c/Windows/Fonts", pattern="arial", prompt=F)
loadfonts(device = "all")
library(patchwork)
library(magick)
library(ggpubr)

```

Data input. 

```{r input, fig.width = 10, fig.height = 5}

git_path <- params$git_path
figure_out_path <- params$figure_out_path

sobj <-readRDS(file.path(git_path,params$object))

```

Subclustering of B cells and Hscs
```{r subc, fig.width = 5, fig.height = 4}
# subclustering 
DefaultAssay(sobj) <- "RNA"

Idents(sobj)<-sobj$CellTypes
sub <- subset(sobj, idents = c("B Cells","Hematopoietic precursor cell"))
sub$CellTypes <- as.factor(sub$CellTypes)
sub$CellTypes <- droplevels(sub$CellTypes)

DefaultAssay(sub) <- "RNA"
sub <-NormalizeData(sub, assay = "RNA", normalization.method='LogNormalize',scale.factor=10000,verbose=FALSE)
sub <- sub %>%
  FindVariableFeatures() %>%
  ScaleData() %>%
  RunPCA(verbose = F) %>%
  RunUMAP(dims = 1:20) 
sub <- FindNeighbors(sub, dims = 1:20, verbose = F)
sub <- FindClusters(sub, verbose = F, resolution = 0.6)
table(sub [[]]$seurat_clusters)
```

Cluster Annotation.
```{r annot}

Idents(sub)<-sub$seurat_clusters
new.cluster.ids <- c( "Immature B Cells", "Mature B Cells", "Hematopoietic precursor cell", "Immature B Cells","Hematopoietic precursor cell","Hematopoietic precursor cell", "Pre / Pro B Cells", "Hematopoietic precursor cell", "Pre / Pro B Cells")
names(new.cluster.ids) <- levels(sub)
sub <- RenameIdents(sub, new.cluster.ids)
sub$CellType<-Idents(sub)

```


pseudotime analysis
```{r pseudo}

sub.sce <- sub %>%
  as.SingleCellExperiment()

colData(sub.sce)$CellType <- as.character(sub$CellType)

reducedDim(sub.sce, "UMAP", withDimnames=TRUE) <- sub[['umap']]@cell.embeddings
reducedDim(sub.sce, "PCA", withDimnames=TRUE) <- sub[['pca']]@cell.embeddings

sub.sce  <- sub.sce %>%
  slingshot(clusterLabels = 'CellType', reducedDim = 'UMAP',start.clus = "Hematopoietic precursor cell")

```

Add pseudotome to Seurat object.

```{r add to seurat}


sub[['avg_pseudotime']] <- slingAvgPseudotime(sub.sce)
sub[['pseudotime_lin1']] <- sub.sce$slingPseudotime_1

```

```{r repair some metadata}

sub$Age_raw<-NULL
Idents(sub)<-sub$age_strain
new.cluster.ids <- c("Young","ImmunoAged","Aged")
names(new.cluster.ids) <- levels(sub)
sub$Age_raw<-Idents(sub)

add_meta_strain <- sub[[]] %>%
  tibble::rownames_to_column("cells") %>%
  select(cells, Age_raw) %>%
  mutate(Age_raw=ifelse(Age_raw=="12w_nonSPF", "Young",
                       ifelse(Age_raw=="26w_nonSPF", "ImmunoAged", 
                              ifelse(Age_raw=="26w_SPF", "Aged", NA)))) %>%
  select(cells, Age_raw) %>%
  tibble::column_to_rownames("cells")

sub <- AddMetaData(sub, metadata = add_meta_strain)

```

Write object.


```{r write}

saveRDS(sub, file.path(git_path, "Figures/data/HSC_pseudotime_correct_redone.rds"))
```


```{r sessionInfo}
sessionInfo()
```

