---
output: 
  html_document:
    df_print: paged
    code_folding: hide
params:
  title: "Bitfam"
  object: "Figures/data/sobj_group_force_final_version.rds"
  git_path: "/mnt/d/work/mireille/fracture-healing-and-aging-scseq"
  figure_out_path: "/mnt/d/onedrive/OneDrive - Charité - Universitätsmedizin Berlin/Third version/Figures/redone/"
title: "`r params$title`"
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy=FALSE, message=FALSE, warning=FALSE)

suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(BITFAM))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(gtools))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(patchwork))

options(future.globals.maxSize = 12 * 1024 * 1024^2)

```

For this analysis, we used the following parameters:

```{r print parameters}

pars <- as.data.frame(do.call("rbind", params))
colnames(pars) <- "parameters_used"
pars

```

Load Seurat object.

```{r read_object, fig.height=4, fig.width=8}

git_path <- params$git_path
figure_out_path <- params$figure_out_path

sobj <- readRDS(file=file.path(git_path,params$object))
```



Renaming the Age group
```{r rename group}

sobj$Age_raw<-NULL
Idents(sobj)<-sobj$age_strain
new.cluster.ids <- c("Young","Immune-aged","Aged")
names(new.cluster.ids) <- levels(sobj)
sobj$Age_raw<-Idents(sobj)

add_meta_strain <- sobj[[]] %>%
  tibble::rownames_to_column("cells") %>%
  select(cells, Age_raw) %>%
  mutate(strain=ifelse(Age_raw=="12w_nonSPF", "Young",
                       ifelse(Age_raw=="26w_nonSPF", "Immune-aged", 
                              ifelse(Age_raw=="26w_SPF", "Aged", NA)))) %>%
  select(cells, strain) %>%
  tibble::column_to_rownames("cells")

sobj <- AddMetaData(sobj, metadata = add_meta_strain)

```

Renaming a few cell types.
```{r rename cells}

Idents(sobj)<-sobj$seurat_clusters
new.cluster.ids <- c( "Monocytes", "Neutrophils", "Myeloid Precursor", "Monocytes", "Eosinophils",
                      "Monocytes", "Dendritic Cells", "Neutrophils", "Myeloid Precursor", "Myeloid Precursor",
                      "Myeloid Precursor", "T Cells", "Neutrophils", 
                      "B Cells","Monocytes", "B Cells","HPCs","Monocytes","T Cells","Neutrophils","Monocytes", "Monocytes","NK Cells","Basophils","Monocytes","HPCs","Erythroblast","B Cells","Eosinophils","Monocytes","Plasma Cells")

names(new.cluster.ids) <- levels(sobj)
sobj <- RenameIdents(sobj, new.cluster.ids)
sobj$CellTypes<-Idents(sobj)

```

```{r bitfam, eval=F}
# all data
# mtx <- GetAssayData(sobj, layer = "counts")
# 
# data_matrix_normalized <- BITFAM_preprocess(raw_data = mtx)

# only b cells, monocytes, fx and aged/immune-aged
data_matrix_normalized <- sobj %>%
  subset(CellTypes %in% c("B Cells", "Monocytes")) %>%
  subset(compartment=="fx" & (strain=="Aged"|strain=="Immune-aged")) %>%
  GetAssayData(layer = "data")
  
BITFAM_res <- BITFAM(data = data_matrix_normalized, species = "mouse", scATAC_obj = NA, ncores = parallel::detectCores())


```


```{r get results, eval = F}

Z <- BITFAM_activities(BITFAM_res)

saveRDS(Z, "BITFAM_activities.rds")
```

```{r read bitfam results}

Z <- readRDS(file.path(git_path, "Figures/data/BITFAM_activities_all_data.rds"))

```

```{r tsne, eval=F}

library(ggplot2)
library(Rtsne)

Z_tsne <- as.data.frame(Rtsne(Z)$Y)
colnames(Z_tsne) <- c("tSNE_1", "tSNE_2")

Annotation <- sobj[[]] %>%
  filter(CellTypes %in% c("B Cells", "Monocytes")) %>%
  filter(compartment=="fx" & (strain=="Aged"|strain=="Immune-aged"))

Annotation <- sobj[[]] 
  
Z_tsne$Cell_type <- Annotation$CellTypes
ggplot(Z_tsne, aes(tSNE_1, tSNE_2, color = Cell_type)) + 
  geom_point(size=0.8)
```
```{r}
ann <- sobj[[]] %>%
  filter(CellTypes %in% c("B Cells", "Monocytes")) %>%
  filter(compartment=="fx" & (strain=="Aged"|strain=="Immune-aged")) %>%
  tibble::rownames_to_column("cells") %>%
  select(cells,CellTypes, compartment, strain, timepoint) %>%
  mutate(group=paste0(CellTypes, "_", strain, "_", timepoint, "_", compartment))

ann_df <- data.frame(
  celltype=ann$CellTypes,
  cells=ann$cells,
  Monocytes_Immune_aged_2days_fx=ifelse(ann$group=="Monocytes_Immune-aged_2days_fx",1,0),
  B_Cells_Immune_aged_2days_fx=ifelse(ann$group=="B Cells_Immune-aged_2days_fx",1,0),
  Monocytes_Immune_aged_5days_fx=ifelse(ann$group=="Monocytes_Immune-aged_5days_fx",1,0),
  B_Cells_Immune_aged_5days_fx=ifelse(ann$group=="B Cells_Immune-aged_5days_fx",1,0),
  B_Cells_Aged_2days_fx=ifelse(ann$group=="B Cells_Aged_2days_fx",1,0),
  Monocytes_Aged_2days_fx=ifelse(ann$group=="Monocytes_Aged_2days_fx",1,0),
  Monocytes_Aged_5days_fx=ifelse(ann$group=="Monocytes_Aged_5days_fx",1,0),
  B_Cells_Aged_5days_fx=ifelse(ann$group=="B Cells_Aged_5days_fx",1,0)
                    )
# df_Z <- as.data.frame(Z)[ann_df$cells,] %>%
#   mutate(B_Cells_Immune_aged_5days_fx=factor(ann_df$B_Cells_Immune_aged_5days_fx))
# library(randomForest)
# fit_rf <- randomForest(B_Cells_Immune_aged_5days_fx~., data = df_Z)  ## build the RF model 
# B_Cells_Immune_aged_5days_fx_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]
# 
# df_Z <- as.data.frame(Z)[ann_df$cells,] %>%
#   mutate(B_Cells_Immune_aged_2days_fx=factor(ann_df$B_Cells_Immune_aged_2days_fx))
# library(randomForest)
# fit_rf <- randomForest(B_Cells_Immune_aged_2days_fx~., data = df_Z)  ## build the RF model 
# B_Cells_Immune_aged_2days_fx_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]





df_Z <- as.data.frame(Z)[ann_df$cells,] %>%
  mutate(Monocytes_Immune_aged_5days_fx=factor(ann_df$Monocytes_Immune_aged_5days_fx))
library(randomForest)
fit_rf <- randomForest(Monocytes_Immune_aged_5days_fx~., data = df_Z)  ## build the RF model 
Monocytes_Immune_aged_5days_fx_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]
# names(Monocytes_Immune_aged_5days_fx_tf_top10) <- paste0("Monocytes_Immune_aged_5days_fx","_",names(Monocytes_Immune_aged_5days_fx_tf_top10))

df_Z <- as.data.frame(Z)[ann_df$cells,] %>%
  mutate(Monocytes_Immune_aged_2days_fx=factor(ann_df$Monocytes_Immune_aged_2days_fx))
library(randomForest)
fit_rf <- randomForest(Monocytes_Immune_aged_2days_fx~., data = df_Z)  ## build the RF model 
Monocytes_Immune_aged_2days_fx_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]
# names(Monocytes_Immune_aged_2days_fx_tf_top10) <- paste0("Monocytes_Immune_aged_2days_fx","_",names(Monocytes_Immune_aged_2days_fx_tf_top10))

df_Z <- as.data.frame(Z)[ann_df$cells,] %>%
  mutate(Monocytes_Aged_5days_fx=factor(ann_df$Monocytes_Aged_5days_fx))
library(randomForest)
fit_rf <- randomForest(Monocytes_Aged_5days_fx~., data = df_Z)  ## build the RF model 
Monocytes_Aged_5days_fx_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]
# names(Monocytes_Aged_5days_fx_tf_top10)<-paste0("Monocytes_Aged_5days_fx","_",names(Monocytes_Aged_5days_fx_tf_top10))


df_Z <- as.data.frame(Z)[ann_df$cells,] %>%
  mutate(Monocytes_Aged_2days_fx=factor(ann_df$Monocytes_Aged_2days_fx))
library(randomForest)
fit_rf <- randomForest(Monocytes_Aged_2days_fx~., data = df_Z)  ## build the RF model 
Monocytes_Aged_2days_fx_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]
# names(Monocytes_Aged_2days_fx_tf_top10)<-paste0("Monocytes_Aged_2days_fx","_",names(Monocytes_Aged_2days_fx_tf_top10))

cols <- c(paste0("Monocytes_Immune_aged_5days_fx","_",names(Monocytes_Immune_aged_5days_fx_tf_top10)),
          paste0("Monocytes_Immune_aged_2days_fx","_",names(Monocytes_Immune_aged_2days_fx_tf_top10)),
          paste0("Monocytes_Aged_5days_fx","_",names(Monocytes_Aged_5days_fx_tf_top10)),
          paste0("Monocytes_Aged_2days_fx","_",names(Monocytes_Aged_5days_fx_tf_top10)))
          


df <- cbind(df_Z[,names(Monocytes_Immune_aged_5days_fx_tf_top10)],
      df_Z[,names(Monocytes_Immune_aged_2days_fx_tf_top10)],
      df_Z[,names(Monocytes_Aged_5days_fx_tf_top10)],
      df_Z[,names(Monocytes_Aged_2days_fx_tf_top10)])
plot_cols <- colnames(df)
colnames(df) <- cols
plot <- apply(df, 2, function(x) (x-min(x))/(max(x)-min(x))) %>%
  as.data.frame() %>%
  tibble::rownames_to_column("cells")

library(dplyr)
data_fr <- plot %>% 
  pivot_longer(cols=colnames(df),names_to="TF", values_to="activity") %>%
  mutate(group=sub("_fx.*","_fx",sub(".*;","", sub("_", ";",TF)))) %>%
  mutate(TF=factor(sub(".*_","",TF)))
  




ggplot(data_fr, mapping = aes(x = cells, y = TF, fill = activity)) + geom_tile() +
  scale_fill_gradient(low = "white",    
                      high = "red",
                      name = "Activity") +
  facet_grid(facets = ~group,
             drop = TRUE,
             space = "free",
             scales = "free",
             aes(fill=cell_type)) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), 
        axis.title.y=element_blank(),
        axis.text.y=element_text(size = 12, face="bold"), 
        strip.text = element_text("none")) 

```

```{r random forest}
Annotation <- read.table(system.file("extdata", "liver_cell_type.txt", package = "BITFAM"), stringsAsFactors = F, sep = "\t")

cell_type_df <- data.frame(Hepatocytes = ifelse(Annotation$cell_types == "Hepatocytes", 1, 0),
                           EPCAM = ifelse(Annotation$cell_types == "EPCAM+", 1, 0),
                           Kupffer = ifelse(Annotation$cell_types == "Kupffer cell", 1, 0),
                           LSEC = ifelse(Annotation$cell_types == "LSEC", 1, 0))
# colnames(Z.vb.beta.prior)[20] <- "NKX3_1"

Annotation <- sobj[[]] 

library(randomForest)
Z <- as.data.frame(Z)
Z_Hepatocytes <- cbind(Z, cell_type_df$Hepatocytes) 
colnames(Z_Hepatocytes)[157] <- "Hepatocytes"
Z_Hepatocytes$Hepatocytes <- factor(Z_Hepatocytes$Hepatocytes )
fit_rf <- randomForest(Hepatocytes~., data = Z_Hepatocytes)  ## build the RF model 
Hepatocytes_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]  ## Based on the feature importances identify the specific TFs for Hepatocytes

## We repeat this code to the other 3 cell types.

Z_EPCAM <- cbind(Z, cell_type_df$EPCAM)
colnames(Z_EPCAM)[157] <- "EPCAM"
Z_EPCAM$EPCAM <- factor(Z_EPCAM$EPCAM)
fit_rf <- randomForest(EPCAM~., data = Z_EPCAM)
EPCAM_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]

Z_Kupffer <- cbind(Z, cell_type_df$Kupffer)
colnames(Z_Kupffer)[157] <- "Kupffer"
Z_Kupffer$Kupffer <- factor(Z_Kupffer$Kupffer)
fit_rf <- randomForest(Kupffer~., data = Z_Kupffer)
Kupffer_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]

Z_LSEC <- cbind(Z, cell_type_df$LSEC)
colnames(Z_LSEC)[157] <- "LSEC"
Z_LSEC$LSEC <- factor(Z_LSEC$LSEC)
fit_rf <- randomForest(LSEC~., data = Z_LSEC)
LSEC_tf_top10 <- importance(fit_rf)[order(importance(fit_rf)[, 1], decreasing = T), ][1:10]

## Build the inferred TF activities for selected TFs
selected_TF_Z <- Z[, names(c(Hepatocytes_tf_top10, EPCAM_tf_top10, Kupffer_tf_top10, LSEC_tf_top10))]
selected_TF_Z <- apply(selected_TF_Z, 2, function(x) (x-min(x))/(max(x)-min(x)))
label <- Annotation$cell_types

## Build the dataframe for heatmap
data_fr <- data.frame(cells = rep(rownames(selected_TF_Z), each = 40), TF = rep(colnames(selected_TF_Z), 6519), stringsAsFactors = F)
data_fr$activity <- as.vector(as.matrix(t(selected_TF_Z)))
data_fr$cell_type <- factor(rep(label, each = 40))
data_fr$TF <- factor(data_fr$TF, levels = colnames(selected_TF_Z))

## Generate heatmap figure
ggplot(data_fr, mapping = aes(x = cells, y = TF, fill = activity)) + geom_tile() +
  scale_fill_gradient(low = "white",    
                      high = "red",
                      name = "Activity") +
  scale_y_discrete(position = "right", label = colnames(selected_TF_Z)) +
  facet_grid(facets = ~cell_type,
             drop = TRUE,
             space = "free",
             scales = "free",
             aes(fill=cell_type)) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), 
        axis.title.y=element_blank(),
        axis.text.y=element_text(size = 12, face="bold"), 
        strip.text = element_text("none")) 
```

```{r session}

sessionInfo()

```


