---
output: 
  html_document:
    df_print: paged
    code_folding: hide
params:
  title: "DESeq2 analysis bone healing Fig3"
  git_path: "/mnt/d/work/mireille/fracture-healing-and-aging-scseq"
  figure_out_path: "/mnt/d/onedrive/OneDrive - Charité - Universitätsmedizin Berlin/Third version/Figures/redone/"
  object: "Figures/data/sobj_group_force_final_version.rds"
  shrinkage_type: "normal"
title: "`r params$title`"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy=FALSE, message=FALSE, warning=FALSE)

suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(gtools))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(stringr))

options(future.globals.maxSize = 12 * 1024 * 1024^2)

```

For this Seurat analysis, we used the following parameters:

```{r print parameters}

pars <- as.data.frame(do.call("rbind", params))
colnames(pars) <- "parameters_used"
pars

```

Starting with this Seurat object from Mireille.

```{r read_object, fig.height=4, fig.width=8}

git_path <- params$git_path
sobj <- readRDS(file.path(git_path, params$object))
```


```{r redo counts}

selected_cell_types <- sobj[[]] %>% 
  pull(CellTypes) %>% 
  unique()

# sample <- sobj[[]] %>%
#   select(group,source_name) %>%
#   mutate(sample=paste0(group,"_",source_name)) %>%
#   select(sample)

# sobj <- AddMetaData(sobj, metadata = sample)

# cluster_metadata_3 <- sobj[[]] %>%
#     mutate(age = str_extract(group, "^[0-9]+w")) %>%
#     mutate(strain = str_extract(group, "w(E|SPF|)")) %>% 
#     mutate(time = str_extract(group, "[0-9]+days")) %>%
#     mutate(arm = paste(age, strain, time, sep = "_")) %>%
#     group_by(arm) %>%
#     mutate(pseudoID = sprintf("ID%02d", as.numeric(as.factor(mouse)))) %>% 
#   select(sample, cell_type, group, mouse, age, location, time, strain,pseudoID) %>% 
#   distinct()

expr <- list()

for (cell_type in selected_cell_types) {
 for (sample in unique(sobj[[]]$sample)) {
   # sample <- unique(sobj[[]]$sample)[1]
   # cell_type <- selected_cell_types[1]
   cells <- Cells(sobj)[(sobj@meta.data$sample==sample & sobj$CellTypes==cell_type )  ] 
   cells <- cells[!is.na(cells)]
   if (length(cells) > 1) {
     expr[[paste0(cell_type,';',sample)]] <- rowSums(sobj@assays$RNA@counts[,cells])
   }
 }
}

for (sample in unique(sobj[[]]$sample)) {
 cells <- Cells(sobj)[(sobj@meta.data$sample==sample )]
 cells <- cells[!is.na(cells)]
 expr[[paste0('all;',sample)]] <- rowSums(sobj@assays$RNA@counts[,cells])
}


sample_name <- sub(".*-","",sub(";.*","", sub(';','-',names(expr))))

colData<-data.frame(sample=names(expr),
               cell_type=factor(sub(';.*','',names(expr))),
               sample_name=sample_name,
               group=sub(".*-","",sub("_","-",sub("_","-",sample_name))),
               mouse=gsub("-","_",sub("_.*","",sub("_","-",sample_name))) ,
               age=sub("_.*","",sub(".*-","",sub("_","-",sub("_","-",sample_name)))),
               compartment=sub(".*_", "", sub("_[fpd].*", "", sample_name)),
               time = sub(".*_", "", sub("days.*", "days", sample_name)),
               strain = ifelse(grepl("12w",sample_name), "young",
                               ifelse(grepl("26w_SPF", sample_name), "aged",
                                      ifelse(grepl("26w_nonSPF", sample_name),"immuno", NA))))

colData <- colData %>%
  mutate(age_time_strain = paste0(age, "_", time, "_", strain)) %>%
  group_by(age_time_strain) %>%
  mutate(pseudoID = sprintf("ID%02d", as.numeric(as.factor(mouse))))%>%
  ungroup()

counts <- do.call(cbind, expr)


```


Get number of reads per sample.
```{r cell numbers,fig.height=10,fig.width=12}

lengths <- colSums(counts)
df_lengths <- data.frame(sample = names(lengths),
                         n_reads = lengths) %>%
  mutate(group = sub(".*-","",sub("_","-",sub("_","-",sub(".*;", "",sample)))),
         celltype = sub(";.*", "", sample))  

ggplot(df_lengths, aes(celltype,n_reads,fill=group))+
  geom_boxplot(position=position_dodge(width=.5),width=.5, outlier.shape = 1, outlier.colour = "red")+
  geom_point(position=position_dodge(width=.5),colour='grey30', shape=1, size=2) +
  facet_wrap(~celltype, scales="free")

```



We run DESeq2 by including the pseudoID in the model. Here we assume that the age_time_location of the mouse is replicated in triplicate (pseudoID). We use all cells, there is not enough cells to look at subtypes.

```{r run de 1}

# selected_cell_types <- c("Monocytes / Macrophages", "Neutrophils", "Myeloid Precursor", "T Cells", "B Cells", "Dendritic Cells", "all")
selected_cell_types <- c("all")
# selected_contrasts <- c("12wfx_5days_vs_12wfx_2days",
#                         "26wEfx_5days_vs_26wEfx_2days",
#                         "26wSPFfx_5days_vs_26wSPFfx_2days",
#                         "26wEfx_2days_vs_12wfx_2days",
#                         "26wSPFfx_2days_vs_12wfx_2days",
#                         "26wSPFfx_2days_vs_26wEfx_2days",
#                         "12wdist_5days_vs_12wfx_5days",
#                         "12wprox_5days_vs_12wfx_5days",
#                         "12wdist_5days_vs_12wprox_5days",
#                         "26wEdist_5days_vs_26wEfx_5days",
#                         "26wEprox_5days_vs_26wEfx_5days",
#                         "26wEdist_5days_vs_26wEprox_5days",
#                         "26wSPFdist_5days_vs_26wSPFfx_5days",
#                         "26wSPFprox_5days_vs_26wSPFfx_5days",
#                         "26wSPFdist_5days_vs_26wSPFprox_5days")

selected_contrasts <- c("12w_nonSPF_5days_fx_vs_12w_nonSPF_2days_fx",
                        "26w_nonSPF_5days_fx_vs_26w_nonSPF_2days_fx",
                        "26w_SPF_5days_fx_vs_26w_SPF_2days_fx",
                        "26w_nonSPF_2days_fx_vs_12w_nonSPF_2days_fx",
                        "26w_SPF_2days_fx_vs_12w_nonSPF_2days_fx",
                        "26w_SPF_2days_fx_vs_26w_nonSPF_2days_fx",
                        "12w_nonSPF_5days_distal_vs_12w_nonSPF_5days_fx",
                        "12w_nonSPF_5days_proximal_vs_12w_nonSPF_5days_fx",
                        "12w_nonSPF_5days_distal_vs_12w_nonSPF_5days_proximal",
                        "26w_nonSPF_5days_distal_vs_26w_nonSPF_5days_fx",
                        "26w_nonSPF_5days_proximal_vs_26w_nonSPF_5days_fx",
                        "26w_nonSPF_5days_distal_vs_26w_nonSPF_5days_proximal",
                        "26w_SPF_5days_distal_vs_26w_SPF_5days_fx",
                        "26w_SPF_5days_proximal_vs_26w_SPF_5days_fx",
                        "26w_SPF_5days_distal_vs_26w_SPF_5days_proximal")
                        
      


# all_groups <- colData$group %>%
#   unique()
# contrasts <- expand_grid(perturbation=all_groups, reference=all_groups) %>%
#       filter(perturbation < reference) %>%
#       mutate(contrast = paste0(perturbation,"_vs_",reference)) %>%
#       pull(contrast)

res <- list()

for (celltype in selected_cell_types){
  
  coldata_df <- colData %>%
    dplyr::filter(cell_type %in% celltype)
  counts_df <- subset(counts, select = coldata_df$sample)
  if (sum(colSums(counts_df)) != 0){
    dds <- DESeqDataSetFromMatrix(countData=as.matrix(counts_df),
                                  colData=coldata_df,
                                  design=~pseudoID + group)
    contrasts <- selected_contrasts
    sub_res <- list()
    
    for (comparison in contrasts){
      perturbation <- sub("_vs_.*", "", comparison)
      reference <- sub(".*_vs_", "", comparison)
      dds$group <- relevel(dds$group, ref = reference)
      
      if (celltype != "all" & celltype != "all_cells"){
        dds <- estimateSizeFactors(dds, type='poscounts')
        dds <- DESeq(dds, test = 'LRT', reduced = ~1, useT=TRUE, minmu=1e-6, minReplicatesForReplace=Inf)
      } else {
        dds <- estimateSizeFactors(dds)
        dds <- DESeq(dds)
      }
      
      if(params$shrinkage_type=="apeglm"){
        sub_res[[comparison]] <- lfcShrink(dds, coef=paste0("group_",comparison), type=params$shrinkage_type, format="DataFrame") %>%
          as.data.frame() %>%
          tibble::rownames_to_column('gene_name') %>%
          mutate(cell_type=celltype, contrast = comparison)
      } else {
        
        sub_res[[comparison]] <- lfcShrink(dds, contrast=c("group",perturbation, reference), type=params$shrinkage_type, format="DataFrame") %>%
          as.data.frame() %>%
          tibble::rownames_to_column('gene_name') %>%
          mutate(cell_type=celltype, contrast = comparison)
      }
    }
    
  }
  res[[celltype]] <- do.call("rbind", sub_res) %>%
    tibble::remove_rownames()
}

res_df <- do.call("rbind", res) %>%
  tibble::remove_rownames()


```



```{r volc1, fig.width=6.5,fig.height=6.5}
for (comparison in unique(res_df$contrast)){
  p <- res_df %>%                  
    dplyr::filter(!is.na(padj), contrast == comparison) %>%
    ggplot(aes(x=log2FoldChange,y=-log10(pvalue),color=padj < .05)) + 
    geom_point(size=.5, shape=1) +
    geom_label_repel(data=res_df %>%
                       dplyr::filter(contrast == comparison,padj < .05),
                     aes(label=gene_name),
                     segment.size=.25,segment.alpha=.5,size=3,color='black',max.overlaps=40,
                     label.padding=0.05,label.size=NA) +
    scale_color_manual(values=c('black','red')) +
    theme_classic() +
    theme(legend.position='none',
          strip.background=element_blank())+
    ggtitle(comparison)+
    facet_wrap(~cell_type, ncol = 2, scales = "free")
  print(p)
  
}
```

```{r ma100, fig.width=9,fig.height=9}
# for (comparison in unique(res_df$contrast)){
#   p <- res_df %>%
#     dplyr::filter(contrast == comparison) %>%
#     ggplot(aes(x=baseMean,y=log2FoldChange,color=padj < .05)) +
#     geom_point(size=.5, shape=1) +
#     geom_label_repel(data=res_df %>%
#                        dplyr::filter(contrast == comparison, padj < .05),
#                      aes(label=gene_name),
#                      segment.size=.25,segment.alpha=.5,size=3,color='black',max.overlaps=30,
#                      label.padding=0.05,label.size=NA) +
#     scale_color_manual(values=c('black','red')) +
#     scale_x_continuous(trans='log10') +
#     coord_cartesian(ylim =c(-4,4)) +
#     theme_classic() +
#     theme(legend.position='none',
#           strip.background=element_blank())+
#     ggtitle(comparison)+
#     facet_wrap(~cell_type, ncol = 2)
#   print(p)
# }
```

```{r res stats100, fig.width=7,fig.height=6}

res_df %>%
  dplyr::arrange(padj) %>%
  dplyr::filter(!is.na(padj) & (padj < .05)) %>%
  dplyr::mutate_if(is.numeric, signif, 2) %>%
  DT::datatable(rownames=FALSE, extensions = 'Buttons', options = list(dom='frtBip', buttons = c('csv')))

dir.create("results_list_310124", recursive=T, showWarnings=T)
write.table(res_df,file.path(git_path,"Figures/data/de_results_pseudoid_analysis_redone.tsv"), quote=F, sep="\t",row.names = F)
```




```{r session}

sessionInfo()

```


