---
author: "Mireille Ngokingha Tchouto and Miha Milek"
output: 
  html_document:
    df_print: paged
    code_folding: hide
params:
  title: "Monocle"
  git_path: "/mnt/d/work/mireille/fracture-healing-and-aging-scseq"
  figure_out_path: "/mnt/d/onedrive/OneDrive - Charité - Universitätsmedizin Berlin/Third version/Figures/redone/"
  object: "Figures/data/HSC_pseudotime_correct.rds"
---

```{r setup, include=FALSE}
library(slingshot)
library(magrittr)
library(pheatmap)
library(tibble)
library(scater)
library(httr)
library(Seurat)
library(dplyr)
library(stringr)
library(ggplot2)
library(cowplot)
library(igraph)
library(Matrix)
library(tidyr)
library(tidyverse)
library(RCurl)
library(plyr)
library(DESeq2)
library(plyr)
library(gtools)
library(biomaRt)
library(AnnotationHub)
library(org.Hs.eg.db)
library(clusterProfiler)
library(org.Mm.eg.db)
library(SingleR)
library(tibble)
library(SingleCellExperiment)
library(scran)
library(apeglm)
library(ashr)
library(sctransform)
library(RColorBrewer)
library(BiocParallel)
library(extrafont)
library(Rttf2pt1) # v1.3.8 or lower
# font_import(paths="/mnt/c/Windows/Fonts", pattern="arial", prompt=F)
loadfonts(device = "all")
library(patchwork)
library(magick)
library(monocle3)
library(SeuratWrappers)
```

```{r paths}

git_path <- params$git_path

figure_out_path <- params$figure_out_path

dir.create(figure_out_path, showWarnings = F, recursive = T)

``` 


###############################################
running the trajectory analysis with monocle. Input is the smaller Seurat object after slingshot analysis. See Scripts/slingshot.Rmd.
```{r run}

sub <- readRDS(file.path(git_path, params$object))
Idents(sub)<-sub$seurat_clusters
new.cluster.ids <- c( "Immature B Cells", "Mature B Cells", "HPCs", "Immature B Cells",
                      "HPCs","HPCs", "Pre / Pro B Cells", "HPCs", "Pre / Pro B Cells")
names(new.cluster.ids) <- levels(sub)
sub <- RenameIdents(sub, new.cluster.ids)
sub$CellType<-Idents(sub)

cds <- as.cell_data_set(sub,assay="integrated")
```

```{r pressure, echo=FALSE}
# head(colData(cds))
# fData(cds)
fData(cds)$gene_short_name <- rownames(fData(cds))
#head(fData(cds))
########## get counts ###################
# head(counts(cds))
```

Retrieve clustering information from Seurat object
```{r retrieve}
recreate.partitions <- c(rep(1, length(cds@colData@rownames)))
names(recreate.partitions) <- cds@colData@rownames
recreate.partitions <- as.factor(recreate.partitions)

cds@clusters@listData[["UMAP"]][["partitions"]] <- recreate.partitions
```

Assign cluster information
```{r assign}
list.cluster <- sub@active.ident
cds@clusters@listData[["UMAP"]][["clusters"]] <- list.cluster
```

Assign UMAP coordinates
```{r coords}
cds@int_colData@listData[["reducedDims"]]@listData[["UMAP"]] <- sub@reductions$umap@cell.embeddings
```

Plot
```{r plot}
cluster.before.traj <-plot_cells(cds, color_cells_by = "cluster", label_groups_by_cluster = F, 
                                 group_label_size = 5) + theme(legend.position = "right")
```

```{r before traj}
cluster.before.traj
```

Learn Trajectory
```{r learn}
cds <- learn_graph(cds, use_partition = T)
```

```{r plot cells}
plot_cells(cds, color_cells_by = "CellType", label_groups_by_cluster = F,
           label_branch_points = T, label_roots = T, label_leaves = F,
           group_label_size = 5)
```

Order cells in Pseudotime
```{r order}
cds <- order_cells(cds, reduction_method = "UMAP", root_cells = NULL)
plot_cells(cds, color_cells_by = "pseudotime", label_groups_by_cluster = T,
           label_branch_points = T, label_roots = F, label_leaves = F)
```

Cells ordered by Monocle3 Pseudotime
```{r ordered}
head(pseudotime(cds), 10)
cds$monocle3_pseudotime <- pseudotime(cds)
data.pseudo <- as.data.frame(colData(cds))

ggplot(data.pseudo, aes(monocle3_pseudotime, CellType, fill = CellType)) + geom_boxplot()

#################### ordered cells #######################
ggplot(data.pseudo, aes(monocle3_pseudotime, reorder(CellType, monocle3_pseudotime), fill = CellType)) + geom_boxplot()
```

save pseudotime

```{r save}

ps <- pseudotime(cds) %>%
  as.data.frame() %>%
  tibble::rownames_to_column("cell_id")

colnames(ps) <- c("cell_id", "pseudotime")
write.table(ps, file.path(git_path,"Figures/data/monocle_pseudotime_redone.tsv"), row.names = F, sep="\t", quote=F)

```

```{r session}

sessionInfo()
```

