---
output: 
  html_document:
    df_print: paged
    code_folding: hide
params:
  title: "Nichenetr differential analysis"
  object: "Figures/data/sobj_group_force_final_version.rds"
  git_path: "/data/cephfs-1/work/groups/cubi/projects/2023-11-30_Fracture_healing_and_aging_scSeq_Mireille_Miha/fracture-healing-and-aging-scseq"
  figure_out_path: "/mnt/d/onedrive/OneDrive - Charité - Universitätsmedizin Berlin/Third version/Figures/redone/"
  gene_info: "Figures/data/gene_id_name_type.tsv"
title: "`r params$title`"
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy=FALSE, message=FALSE, warning=FALSE)

suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(gtools))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(nichenetr))
suppressPackageStartupMessages(library(SeuratObject))
suppressPackageStartupMessages(library(tidyverse))


options(future.globals.maxSize = 12 * 1024 * 1024^2)

```

For this analysis, we used the following parameters:

```{r print parameters}

pars <- as.data.frame(do.call("rbind", params))
colnames(pars) <- "parameters_used"
pars

```

Load Seurat object.

```{r read_object, fig.height=4, fig.width=8}

git_path <- params$git_path
figure_out_path <- params$figure_out_path

sobj <- readRDS(file=file.path(git_path,params$object))
```



Renaming the Age group
```{r rename group}

sobj$Age_raw<-NULL
Idents(sobj)<-sobj$age_strain
new.cluster.ids <- c("Young","Immune-aged","Aged")
names(new.cluster.ids) <- levels(sobj)
sobj$Age_raw<-Idents(sobj)

add_meta_strain <- sobj[[]] %>%
  tibble::rownames_to_column("cells") %>%
  select(cells, Age_raw,compartment,timepoint) %>%
  mutate(strain=ifelse(Age_raw=="12w_nonSPF", "Young",
                       ifelse(Age_raw=="26w_nonSPF", "Immune-aged", 
                              ifelse(Age_raw=="26w_SPF", "Aged", NA)))) %>%
  mutate(compartment=ifelse(compartment=="fx", "hematoma", compartment)) %>%
  mutate(group=paste0(strain,"_",timepoint,"_",compartment)) %>%
  select(cells, strain, group) %>%
  tibble::column_to_rownames("cells")

sobj <- AddMetaData(sobj, metadata = add_meta_strain)

```

Renaming a few cell types.
```{r rename cells}

Idents(sobj)<-sobj$seurat_clusters
new.cluster.ids <- c( "Monocytes", "Neutrophils", "Myeloid Precursor", "Monocytes", "Eosinophils",
                      "Monocytes", "Dendritic Cells", "Neutrophils", "Myeloid Precursor", "Myeloid Precursor",
                      "Myeloid Precursor", "T Cells", "Neutrophils", 
                      "B Cells","Monocytes", "B Cells","HPCs","Monocytes","T Cells","Neutrophils","Monocytes", "Monocytes","NK Cells","Basophils","Monocytes","HPCs","Erythroblast","B Cells","Eosinophils","Monocytes","Plasma Cells")

names(new.cluster.ids) <- levels(sobj)
sobj <- RenameIdents(sobj, new.cluster.ids)
sobj$CellTypes<-Idents(sobj)

```

Define differential niches.

```{r diff}
# niches = list(
#     "Immune-aged_5days_hematoma" = list(
#       "sender" = c("Monocytes_Immune-aged_5days_hematoma"),
#       "receiver" = c("B Cells_Immune-aged_5days_hematoma")),
#     "Immune-aged_2days_hematoma" = list(
#       "sender" = c("Monocytes_Immune-aged_2days_hematoma"),
#       "receiver" = c("B Cells_Immune-aged_2days_hematoma")),
#     "Aged_5days_hematoma" = list(
#       "sender" = c("Monocytes_Aged_5days_hematoma"),
#       "receiver" = c("B Cells_Aged_5days_hematoma")),
#     "Aged_2days_hematoma" = list(
#       "sender" = c("Monocytes_Aged_2days_hematoma"),
#       "receiver" = c("B Cells_Aged_2days_hematoma"))
#   )


niches = list(
    "Immune-aged_5days_hematoma" = list(
      "sender" = c("Monocytes_Immune-aged_5days_hematoma"),
      "receiver" = c("B Cells_Immune-aged_5days_hematoma")),
    "Aged_5days_hematoma" = list(
      "sender" = c("Monocytes_Aged_5days_hematoma"),
      "receiver" = c("B Cells_Aged_5days_hematoma"))
  )

# niches = list(
#     "Immune-aged_5days_hematoma" = list(
#       "sender" = c("Monocytes_Immune-aged_5days_hematoma"),
#       "receiver" = c("B Cells_Immune-aged_5days_hematoma")),
#     "Immune-aged_2days_hematoma" = list(
#       "sender" = c("Monocytes_Immune-aged_2days_hematoma"),
#       "receiver" = c("B Cells_Immune-aged_2days_hematoma"))
#   )

# 
# niche_a = list(
#     "Aged_5days_hematoma" = list(
#       "sender" = c("Monocytes_Aged_5days_hematoma"),
#       "receiver" = c("B Cells_Aged_5days_hematoma")),
#     "Aged_2days_hematoma" = list(
#       "sender" = c("Monocytes_Aged_2days_hematoma"),
#       "receiver" = c("B Cells_Aged_2days_hematoma"))
#   )


``` 

Begin differential analysis

```{r}

celltype_group <- sobj[[]] %>%
  tibble::rownames_to_column("cells") %>%
  mutate(celltype_group = paste0(CellTypes, "_", group)) %>%
  select(cells, celltype_group) %>%
  tibble::column_to_rownames("cells")

sobj_diff <- AddMetaData(sobj, metadata = celltype_group)

sobj_diff <- SetIdent(sobj_diff, value= "celltype_group")

organism = "mouse" # user adaptation required on own dataset

if(organism == "mouse"){
  lr_network = readRDS(url("https://zenodo.org/record/7074291/files/lr_network_mouse_21122021.rds"))
  ligand_target_matrix = readRDS(url("https://zenodo.org/record/7074291/files/ligand_target_matrix_nsga2r_final_mouse.rds"))
}

lr_network = lr_network %>% dplyr::rename(ligand = from, receptor = to) %>% distinct(ligand, receptor)

```


Calculate differential expression between the niches.

```{r}
assay_oi = "RNA"

DE_sender = calculate_niche_de(seurat_obj = sobj_diff %>% subset(features = lr_network$ligand %>% intersect(rownames(sobj_diff))), niches = niches, type = "sender", assay_oi = assay_oi) # only ligands important for sender cell types

DE_receiver = calculate_niche_de(seurat_obj = sobj_diff %>% subset(features = lr_network$receptor %>% unique()), 
                                 niches = niches, type = "receiver", assay_oi = assay_oi) # only receptors now, later on: DE analysis to find targets



```

```{r}

DE_sender = DE_sender %>% mutate(avg_log2FC = ifelse(avg_log2FC == Inf, max(avg_log2FC[is.finite(avg_log2FC)]), ifelse(avg_log2FC == -Inf, min(avg_log2FC[is.finite(avg_log2FC)]), avg_log2FC)))

DE_receiver = DE_receiver %>% mutate(avg_log2FC = ifelse(avg_log2FC == Inf, max(avg_log2FC[is.finite(avg_log2FC)]), ifelse(avg_log2FC == -Inf, min(avg_log2FC[is.finite(avg_log2FC)]), avg_log2FC)))

```

```{r}

expression_pct = 0.01

DE_sender_processed = process_niche_de(DE_table = DE_sender, niches = niches, expression_pct = expression_pct, type = "sender")
DE_receiver_processed = process_niche_de(DE_table = DE_receiver, niches = niches, expression_pct = expression_pct, type = "receiver")

specificity_score_LR_pairs = "mean_lfc"
DE_sender_receiver = combine_sender_receiver_de(DE_sender_processed, DE_receiver_processed, lr_network, specificity_score = specificity_score_LR_pairs)

```

Calculate ligand activities.

```{r}

expression_pct = 0.01
lfc_cutoff = 0.15 # recommended for 10x as min_lfc cutoff 0.15
specificity_score_targets = "mean_lfc"

DE_receiver_targets = calculate_niche_de_targets(seurat_obj = sobj_diff, niches = niches, lfc_cutoff = lfc_cutoff, expression_pct = expression_pct, assay_oi = assay_oi) 

## calculate niche DE receiver targets ( B cells ), DE_receiver_targets can be defined differently, eg from pseudobulk diff expression results, must have columns:
## "receiver"             "receiver_other_niche" "gene"                 "p_val"                "avg_log2FC"          
## "pct.1"                "pct.2"                "p_val_adj"

DE_receiver_processed_targets = process_receiver_target_de(DE_receiver_targets = DE_receiver_targets, niches = niches, expression_pct = expression_pct, specificity_score = specificity_score_targets)

background = DE_receiver_processed_targets  %>% pull(target) %>% unique()
geneset_niche1 = DE_receiver_processed_targets %>% filter(receiver == niches[[1]]$receiver & target_score >= lfc_cutoff  & target_present == 1) %>% pull(target) %>% unique()
geneset_niche2 = DE_receiver_processed_targets %>% filter(receiver == niches[[2]]$receiver & target_score >= lfc_cutoff & target_present == 1) %>% pull(target) %>% unique()

top_n_target = 250

niche_geneset_list = list(
  "Immune-aged_5days_hematoma" = list(
    "receiver" = niches[[1]]$receiver,
    "geneset" = geneset_niche1,
    "background" = background),
  "Immune-aged_2days_hematoma" = list(
    "receiver" = niches[[2]]$receiver,
    "geneset" = geneset_niche2 ,
    "background" = background)
  )

ligand_activities_targets = get_ligand_activities_targets(niche_geneset_list = niche_geneset_list, ligand_target_matrix = ligand_target_matrix, top_n_target = top_n_target)

```

Calculate scaled ligand, receptor and target expression 

```{r}

features_oi = union(lr_network$ligand, lr_network$receptor) %>% union(ligand_activities_targets$target) %>% setdiff(NA)
  
dotplot = suppressWarnings(Seurat::DotPlot(sobj_diff %>% subset(idents = niches %>% unlist() %>% unique()), features = features_oi, assay = assay_oi))

exprs_tbl = dotplot$data %>% as_tibble()
exprs_tbl = exprs_tbl %>% rename(celltype = id, gene = features.plot, expression = avg.exp, expression_scaled = avg.exp.scaled, fraction = pct.exp) %>%
    mutate(fraction = fraction/100) %>% as_tibble() %>% select(celltype, gene, expression, expression_scaled, fraction) %>% distinct() %>% arrange(gene) %>% mutate(gene = as.character(gene))
  
exprs_tbl_ligand = exprs_tbl %>% filter(gene %in% lr_network$ligand) %>% rename(sender = celltype, ligand = gene, ligand_expression = expression, ligand_expression_scaled = expression_scaled, ligand_fraction = fraction) 
exprs_tbl_receptor = exprs_tbl %>% filter(gene %in% lr_network$receptor) %>% rename(receiver = celltype, receptor = gene, receptor_expression = expression, receptor_expression_scaled = expression_scaled, receptor_fraction = fraction)
exprs_tbl_target = exprs_tbl %>% filter(gene %in% ligand_activities_targets$target) %>% rename(receiver = celltype, target = gene, target_expression = expression, target_expression_scaled = expression_scaled, target_fraction = fraction)

exprs_tbl_ligand = exprs_tbl_ligand %>%  mutate(scaled_ligand_expression_scaled = scale_quantile_adapted(ligand_expression_scaled)) %>% mutate(ligand_fraction_adapted = ligand_fraction) %>% mutate_cond(ligand_fraction >= expression_pct, ligand_fraction_adapted = expression_pct)  %>% mutate(scaled_ligand_fraction_adapted = scale_quantile_adapted(ligand_fraction_adapted))

exprs_tbl_receptor = exprs_tbl_receptor %>% mutate(scaled_receptor_expression_scaled = scale_quantile_adapted(receptor_expression_scaled))  %>% mutate(receptor_fraction_adapted = receptor_fraction) %>% mutate_cond(receptor_fraction >= expression_pct, receptor_fraction_adapted = expression_pct)  %>% mutate(scaled_receptor_fraction_adapted = scale_quantile_adapted(receptor_fraction_adapted))

```

```{r expression scores}

exprs_sender_receiver = lr_network %>% 
  inner_join(exprs_tbl_ligand, by = c("ligand")) %>% 
  inner_join(exprs_tbl_receptor, by = c("receptor")) %>% inner_join(DE_sender_receiver %>% distinct(niche, sender, receiver))

ligand_scaled_receptor_expression_fraction_df = exprs_sender_receiver %>% group_by(ligand, receiver) %>% mutate(rank_receptor_expression = dense_rank(receptor_expression), rank_receptor_fraction  = dense_rank(receptor_fraction)) %>% mutate(ligand_scaled_receptor_expression_fraction = 0.5*( (rank_receptor_fraction / max(rank_receptor_fraction)) + ((rank_receptor_expression / max(rank_receptor_expression))) ) )  %>% distinct(ligand, receptor, receiver, ligand_scaled_receptor_expression_fraction) %>% distinct() %>% ungroup() 
```

```{r}
prioritizing_weights = c("scaled_ligand_score" = 1,
                         "scaled_ligand_expression_scaled" = .5,
                         "ligand_fraction" = 1,
                         "scaled_ligand_score_spatial" = 2, 
                         "scaled_receptor_score" = 5,
                         "scaled_receptor_expression_scaled" = 1,
                          "receptor_fraction" = 1, 
                         "ligand_scaled_receptor_expression_fraction" = 1,
                         "scaled_receptor_score_spatial" = 0,
                         "scaled_activity" = 5,
                         "scaled_activity_normalized" = 5)
output = list(DE_sender_receiver = DE_sender_receiver, ligand_scaled_receptor_expression_fraction_df = ligand_scaled_receptor_expression_fraction_df, sender_spatial_DE_processed = NULL, receiver_spatial_DE_processed = NULL,
         ligand_activities_targets = ligand_activities_targets, DE_receiver_processed_targets = DE_receiver_processed_targets, exprs_tbl_ligand = exprs_tbl_ligand,  exprs_tbl_receptor = exprs_tbl_receptor, exprs_tbl_target = exprs_tbl_target)

# prioritization_tables = get_prioritization_tables(output, prioritizing_weights)
# does not work due to absence of spatial data


get_prioritization_tables_no_spatial <- function (output_nichenet_analysis, prioritizing_weights) 
{
    combined_information = output_nichenet_analysis$DE_sender_receiver %>% 
        inner_join(output_nichenet_analysis$ligand_scaled_receptor_expression_fraction_df, 
            by = c("receiver", "ligand", "receptor")) %>% inner_join(output_nichenet_analysis$ligand_activities_targets, 
        by = c("receiver", "ligand")) %>% left_join(output_nichenet_analysis$DE_receiver_processed_targets, 
        by = c("niche", "receiver", "target")) %>% inner_join(output_nichenet_analysis$exprs_tbl_ligand, 
        by = c("sender", "ligand")) %>% inner_join(output_nichenet_analysis$exprs_tbl_receptor, 
        by = c("receiver", "receptor")) %>% left_join(output_nichenet_analysis$exprs_tbl_target, 
        by = c("receiver", "target"))
    combined_information = combined_information %>% mutate(ligand_receptor = paste(ligand, 
        receptor, sep = "--"))
    combined_information = combined_information %>% select(niche, 
        receiver, sender, ligand_receptor, ligand, receptor, 
        target, ligand_score, ligand_significant, ligand_present, 
        ligand_expression, ligand_expression_scaled, ligand_fraction, receptor_score, receptor_significant, 
        receptor_present, receptor_expression, receptor_expression_scaled, 
        receptor_fraction, ligand_scaled_receptor_expression_fraction, 
        avg_score_ligand_receptor, target_score, target_significant, 
        target_present, target_expression, target_expression_scaled, 
        target_fraction, ligand_target_weight, activity, activity_normalized, 
        scaled_ligand_score, scaled_ligand_expression_scaled, 
        scaled_receptor_score, scaled_receptor_expression_scaled, 
        scaled_avg_score_ligand_receptor, 
        scaled_ligand_fraction_adapted, 
        scaled_receptor_fraction_adapted, scaled_activity, scaled_activity_normalized) %>% 
        distinct()
    combined_information_prioritized = combined_information %>% 
        dplyr::mutate(prioritization_score = ((prioritizing_weights["scaled_ligand_score"] * 
            scaled_ligand_score) + (prioritizing_weights["scaled_ligand_expression_scaled"] * 
            scaled_ligand_expression_scaled) + (prioritizing_weights["scaled_receptor_score"] * 
            scaled_receptor_score) + (prioritizing_weights["scaled_receptor_expression_scaled"] * 
            scaled_receptor_expression_scaled) +  (prioritizing_weights["ligand_scaled_receptor_expression_fraction"] * 
            ligand_scaled_receptor_expression_fraction) + (prioritizing_weights["scaled_activity"] * 
            scaled_activity) + (prioritizing_weights["scaled_activity_normalized"] * 
            scaled_activity_normalized) + (prioritizing_weights["ligand_fraction"] * 
            scaled_ligand_fraction_adapted) + (prioritizing_weights["receptor_fraction"] * 
            scaled_receptor_fraction_adapted)) * (1/length(prioritizing_weights))) %>% 
        dplyr::arrange(-prioritization_score)
    prioritization_tbl_ligand_receptor = combined_information_prioritized %>% 
        select(niche, receiver, sender, ligand_receptor, ligand, 
            receptor, ligand_score, ligand_significant, ligand_present, 
            ligand_expression, ligand_expression_scaled, ligand_fraction, 
            receptor_score, receptor_significant, 
            receptor_present, receptor_expression, receptor_expression_scaled, 
            receptor_fraction, ligand_scaled_receptor_expression_fraction, 
            avg_score_ligand_receptor, activity, activity_normalized, 
            scaled_ligand_score, scaled_ligand_expression_scaled, 
            scaled_receptor_score, scaled_receptor_expression_scaled, 
            scaled_avg_score_ligand_receptor, 
            scaled_ligand_fraction_adapted, 
            scaled_receptor_fraction_adapted, scaled_activity, 
            scaled_activity_normalized, prioritization_score) %>% 
        distinct()
    prioritization_tbl_ligand_target = combined_information_prioritized %>% 
        select(niche, receiver, sender, ligand_receptor, ligand, 
            receptor, target, target_score, target_significant, 
            target_present, target_expression, target_expression_scaled, 
            target_fraction, ligand_target_weight, activity, 
            activity_normalized, scaled_activity, scaled_activity_normalized, 
            prioritization_score) %>% distinct()
    return(list(prioritization_tbl_ligand_receptor = prioritization_tbl_ligand_receptor, 
        prioritization_tbl_ligand_target = prioritization_tbl_ligand_target))
}


prioritization_tables = get_prioritization_tables_no_spatial(output, prioritizing_weights)

prioritization_tables$prioritization_tbl_ligand_receptor %>% filter(receiver == niches[[1]]$receiver) %>% head(10)

```

```{r preparevisualizing, fig.height=15,fig.width=4}

top_ligand_niche_df = prioritization_tables$prioritization_tbl_ligand_receptor %>% select(niche, sender, receiver, ligand, receptor, prioritization_score) %>% group_by(ligand) %>% top_n(1, prioritization_score) %>% ungroup() %>% select(ligand, receptor, niche) %>% rename(top_niche = niche)
top_ligand_receptor_niche_df = prioritization_tables$prioritization_tbl_ligand_receptor %>% select(niche, sender, receiver, ligand, receptor, prioritization_score) %>% group_by(ligand, receptor) %>% top_n(1, prioritization_score) %>% ungroup() %>% select(ligand, receptor, niche) %>% rename(top_niche = niche)

ligand_prioritized_tbl_oi = prioritization_tables$prioritization_tbl_ligand_receptor %>% select(niche, sender, receiver, ligand, prioritization_score) %>% group_by(ligand, niche) %>% top_n(1, prioritization_score) %>% ungroup() %>% distinct() %>% inner_join(top_ligand_niche_df) %>% filter(niche == top_niche) %>% group_by(niche) %>% top_n(50, prioritization_score) %>% ungroup() # get the top50 ligands per niche

```

```{r visualizing, fig.height=20,fig.width=4}


receiver_oi = "B Cells_Immune-aged_5days_hematoma" 

filtered_ligands = ligand_prioritized_tbl_oi %>% filter(receiver == receiver_oi) %>% pull(ligand) %>% unique()

prioritized_tbl_oi = prioritization_tables$prioritization_tbl_ligand_receptor %>% filter(ligand %in% filtered_ligands) %>% select(niche, sender, receiver, ligand,  receptor, ligand_receptor, prioritization_score) %>% distinct() %>% inner_join(top_ligand_receptor_niche_df) %>% group_by(ligand) %>% filter(receiver == receiver_oi) %>% top_n(10, prioritization_score) %>% ungroup() 

lfc_plot = make_ligand_receptor_lfc_plot(receiver_oi, prioritized_tbl_oi, prioritization_tables$prioritization_tbl_ligand_receptor, plot_legend = FALSE, heights = NULL, widths = NULL)
lfc_plot
```


```{r ligand activity vis, fig.width=30,fig.height=20}
exprs_activity_target_plot = make_ligand_activity_target_exprs_plot(receiver_oi, prioritized_tbl_oi,  prioritization_tables$prioritization_tbl_ligand_receptor,  prioritization_tables$prioritization_tbl_ligand_target, output$exprs_tbl_ligand,  output$exprs_tbl_target, lfc_cutoff, ligand_target_matrix, plot_legend = FALSE, heights = NULL, widths = NULL)
exprs_activity_target_plot$combined_plot
```

```{r ligand activity vis, fig.width=40,fig.height=10}
filtered_ligands = ligand_prioritized_tbl_oi %>% filter(receiver == receiver_oi) %>% top_n(20, prioritization_score) %>% pull(ligand) %>% unique()

prioritized_tbl_oi = prioritization_tables$prioritization_tbl_ligand_receptor %>% filter(ligand %in% filtered_ligands) %>% select(niche, sender, receiver, ligand,  receptor, ligand_receptor, prioritization_score) %>% distinct() %>% inner_join(top_ligand_receptor_niche_df) %>% group_by(ligand) %>% filter(receiver == receiver_oi) %>% top_n(2, prioritization_score) %>% ungroup() 

exprs_activity_target_plot = make_ligand_activity_target_exprs_plot(receiver_oi, prioritized_tbl_oi,  prioritization_tables$prioritization_tbl_ligand_receptor,  prioritization_tables$prioritization_tbl_ligand_target, output$exprs_tbl_ligand,  output$exprs_tbl_target, lfc_cutoff, ligand_target_matrix, plot_legend = FALSE, heights = NULL, widths = NULL)
exprs_activity_target_plot$combined_plot
``` 

```{r circos}
filtered_ligands = ligand_prioritized_tbl_oi %>% filter(receiver == receiver_oi) %>% top_n(15, prioritization_score) %>% pull(ligand) %>% unique()

prioritized_tbl_oi = prioritization_tables$prioritization_tbl_ligand_receptor %>% filter(ligand %in% filtered_ligands) %>% select(niche, sender, receiver, ligand,  receptor, ligand_receptor, prioritization_score) %>% distinct() %>% inner_join(top_ligand_receptor_niche_df) %>% group_by(ligand) %>% filter(receiver == receiver_oi) %>% top_n(2, prioritization_score) %>% ungroup() 

colors_sender = brewer.pal(n = prioritized_tbl_oi$sender %>% unique() %>% sort() %>% length(), name = 'Spectral') %>% magrittr::set_names(prioritized_tbl_oi$sender %>% unique() %>% sort())
colors_receiver = c("lavender")  %>% magrittr::set_names(prioritized_tbl_oi$receiver %>% unique() %>% sort())

circos_output = make_circos_lr(prioritized_tbl_oi, colors_sender, colors_receiver)

```

```{r session}

sessionInfo()

```


