# global parameters

sample_table: all_samples.txt 
# a tab-separated file, look at examples in the github repo
organism: mouse
nFeature_cutoff: 6500
# filtering based on number of genes per cell, usually has to be determined empirically, 5000 is a good starting value
min_cells: 1 
min_features: 250
mito_cutoff: 10
ribo_cutoff: 25
# CreateSeuratObject() parameters
output_rds_dir: out_rds/ 
# trailing slash is necessary
mouse_rds_dir: mouse_rds/
# this directory contains supplied RDS objects for mouse cell cycle gene names, relevant only for mouse datasets
doublet_finder: false
# depending on this the doublet finder rule will be executed or not, should be false if multiplexing was performed
partition: highmem
# which partition to use for integration, e.g. medium or highmem. highmem might be needed for >50000 cells
memory: 100G
# job starting memory in GB for all rules except integration, note that highmem partition is required for >100GB 

# initial analysis

output_initial_html: out/initial_analysis.html 
# name of the output html for initial analysis
title_initial: 'Analysis part 1' 
# title of the initial analysis report
initial_dims: 20
# dimensions for FindNeighbours() and RunUMAP() during initial analysis and doublet finder
initial_resolution: 0.8
# cluster finding resolution for FindClusters() during initial analysis and doublet finder

# doublet finder (optional)
output_df_html: out/doublet_finder.html 
# name of the output html for doublet finder analysis
input_df_object: sobj.separate.cc.rds 
# input rds object from initial analysis, can be either 'sobj.rds', 'sobj.separate.cc.rds' or 'sobj.diff.cc.rds', depending on whether the results of no regression, separate cell cycle score regression, or difference in cell cycle score regression should be used
title_df: 'Analysis part 2' 
# title of the doublet finder report
split_by: sample 
# how should the seurat object be split before doublet finder analysis, corresponds to a column name in sample_table.txt, should almost always be 'sample'
doublet_formation_rate: 0.05 
# this is a parameter for doublet finder, typically 0.05


# integration
integration_time: '04:00:00'
# job duration for integration, might have to increase for large datasets
starting_memory_integration: 100
# job starting memory in GB for integration, note that highmem partition will be required for >100GB 
output_integration_html: out/integration.html 
# name of the output html for integration analysis
input_integration_object: sobj.separate.cc.rds 
# input rds object from initial analysis, depends on whether the doublet finder analysis was performed or not. can be either 'sobj.rds', 'sobj.separate.cc.rds', 'sobj.diff.cc.rds', 'sobj.df.rds', 'sobj.df.separate.cc.rds' or 'sobj.df.diff.cc.rds'
title_integration: 'Analysis part 2' 
# title of the integration report
n_cols: 5 
# number of columns used for the integration report feature plots, adjust this if the rendered images look either too wide or too narrow
integration_dims: 20
# dimensions for FindNeighbours() and RunUMAP() during integration
integration_npcs: 20
# number of principal components for RunPCA() during integration
integration_resolution: 1.0
# cluster finding resolution for FindClusters() during integration
evaluate_reproducibility_on: sample
# this parameter controls, how the results of the integration are evaluated by plotting the percentage of cells per cluster. if sample (default), then no replicate experiments are assumed and a simple barplot will be shown. if eg. group, condition or treatment or any other column from sample table are selected here, then the unique values of that column will be treated as groups of replicate experiments and a boxplot of percentages per group will be shown.

# common report
common_report: false
title_common_report: 'Final report'
common_report_html: out/final_report.html
best_integrated_object: sobj.sample.forced.rds

