---
output: 
  html_document:
    df_print: paged
    code_folding: hide
    code_download: true
    number_sections: true
    toc: true
    toc_float: true
params:
  title: "Analysis Report"
  sample_table: "sample_table.txt"
  input_object: "out_rds/sobj.df.library.forced.rds"
  object_dir: "out_rds/"
  integration_dims: 20
  integration_npcs: 20
  integration_resolution: 1.0
title: |
  | CUBI SCBA Single Cell Pipeline
  | 
  | `r params$title`
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy=FALSE, message=FALSE, warning=FALSE)

suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(gtools))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(yaml))

options(future.globals.maxSize = 12 * 1024 * 1024^2)

sample_df <- read.delim(params$sample_table, header = T)

if (is.na(unique(sample_df$multiplex)) | unique(sample_df$multiplex)=="false" | unique(sample_df$multiplex) == FALSE ){
	multiplex_condition <- FALSE
} else if (length(unique(sample_df$multiplex)) > 1){
	multiplex_condition <- TRUE
}	else {
	stop("Something is wrong with the multiplex setup. Please modify sample table.", call. = FALSE)
}

config <- read_yaml("config.yaml")

```

For this pipeline run, we used the following configuration and sample table.

```{r print parameters}

con <- as.data.frame(do.call("rbind", config))
colnames(con) <- "parameters_used"
con

sample_df
```




```{r sessionInfo}

sessionInfo()
```
